### ISSUE TITLE
MD parsing improvements

### ISSUE THREAD

**Issue by ericecook** [icook/bluelinks#24]
- Auto hyperlinking - http(s)://*
- Link community names  - /c/\*  /community/*
- Link usernames  - /u/\*  /user/*

**Comment by ericecook** [comment]
Done, but requires custom renderer support in flask-misaka. Support for that was added yesterday (https://github.com/singingwolfboy/flask-misaka/pull/7), just waiting on their release cycle.

**Comment by icook** [comment]
You can pin a specific commit from git in the requirements. Looks like this:

```
git+https://github.com/mitsuhiko/flask.git@595fb7e1fac3eea207816a700565f6a549e160d3
```

**Comment by ericecook** [comment]
FYI you also have to include the package name if you specify a commit:

```
git+https://github.com/mitsuhiko/flask.git@595fb7e1fac3eea207816a700565f6a549e160d3#egg=Flask
```
