### ISSUE TITLE
Populate the user profile page

### ISSUE THREAD

**Issue by icook** [icook/bluelinks#3]
Should be pretty quick to get a really basic version working

**Comment by ericecook** [comment]
@icook For now just a list of posts & comments by that user?

**Comment by icook** [comment]
That's what I was thinking. Avoid actually interleaving them and just make tabs. Usually on reddit I only want to see submissions anyway...

**Comment by ericecook** [comment]
554ade5c08907a9571dc1dd40006cc3a9900f599
